name: Build

on:
  release:
    types:
      - published
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - '.github/workflows/pr.yml'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.18'

      - name: go test
        run: go build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.18'

      - name: go test
        run: |
          go test -race -cover ./... -coverprofile coverage.out -coverpkg ./...
          go tool cover -func coverage.out -o coverage.out

      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage.out

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.18'

      - name: golangci-lint run
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: --timeout=3m

