name: Pull Request

on:
  pull_request:
    paths-ignore:
      - '.github/workflows/pr.yml'
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.18'

      - name: go test
        run: go test -race -cover ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.18'

      - name: golangci-lint run
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: --timeout=3m