name: Build

on:
  release:
    types:
      - published
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - '.github/workflows/pr.yml'
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19'

      - name: go test
        run: go build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19'

      - name: go test
        run: |
          go test -race -cover ./... -covermode=atomic -coverprofile coverage.out

      - name: Upload coverage file
        uses: codecov/codecov-action@v3

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19'

      - name: golangci-lint run
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: --timeout=3m

